version: '3.9'
services:
  domain-scanner-app:
    container_name: domain-scanner-app
    build:
      context: ./domain-scanner-app
      dockerfile: Dockerfile
    # command: /bin/sh -c "while sleep 1000; do :; done"
  domain-scanner-ui:
    container_name: domain-scanner-ui
    build:
      context: ./domain-scanner-ui
      dockerfile: .devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"

